version: '3.8'

services:
  node-qx-admin:
    build:
      context: . # Diretório onde está o Dockerfile
    container_name: node-qx-admin
    working_dir: /usr/src/app
    environment:
      VITE_API_BASE_URL: "http://nestjs:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3039:3039" # Porta do servidor Vite
    command: sh -c "npm run start"
