version: '3.8'

services:
  vite-app:
    build:
      context: . # Diretório onde está o Dockerfile
    container_name: vite-app-container
    working_dir: /usr/src/app
    environment:
      VITE_API_BASE_URL: "http://nestjs:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5173:5173" # Porta do servidor Vite
    command: sh -c "npm run dev"
